### ISSUE TITLE
bug about viz_stereo.py

### ISSUE THREAD

**Issue by Smellly** [ubc-vision/image-matching-benchmark#13]
`plt.plot((kp1[idx, 0] + h_offset[0], kp2[idx, 0] + h_offset[1]),`          
should be 
`plt.plot((kp1_inl[idx, 0] + h_offset[0], kp2_inl[idx, 0] + h_offset[1]),`
to plot the rgiht inlier match here ?
https://github.com/vcg-uvic/image-matching-benchmark/blob/0b7307200b312349fcb281ccb6c71409fd651e20/viz_stereo.py#L184

**Comment by kmyi** [comment]
Something does seem weird in the visualization script here ;) Seems like something has been left-off while debugging? @etrulls @jyh2005xx

**Comment by etrulls** [comment]
Good catch, fixed. That explains some odd results we saw here and there. We will regenerate the visualizations soon.

**Comment by etrulls** [comment]
Done!
