### ISSUE TITLE
results of R2D2

### ISSUE THREAD

**Issue by feixue94** [ubc-vision/image-matching-benchmark#14]
hi,
thank you for your sharing. it's really excellent work.  
it seems that the end-to-end method _R2D2: Repeatable
and Reliable Detector and Descriptor_ is cited but not evaluated in your paper.

**Comment by etrulls** [comment]
There are three R2D2 entries in the challenge leaderboards already. We plan to add it to a new version of the paper that we are working on.

If you'd like to see other features, please consider sending us a submission (we cannot run every single baseline ourselves).
