### ISSUE TITLE
How to generate "new-vis-pairs/keys-th-0.1.npy"

### ISSUE THREAD

**Issue by sailor-z** [ubc-vision/image-matching-benchmark#15]
Hi,

Thanks for releasing the benchmark. I'd like to pair images in training and validation sets, but I have a issue about the  "new-vis-pairs/keys-th-{}.npy". I've used two different methods to generate image pairs. The first one is loading "imw2020-valid/reichstag/set_100/new-vis-pairs/keys-th-{}.npy", and the second one is as follows
![image](https://user-images.githubusercontent.com/26895204/79630630-8d54cd80-8185-11ea-978f-222b655d1eb1.png).
I got two different results. For example in "sacre_coeur", the first one generates 3373 image pairs with the threshold 0.2, but the second one generates 442645 pairs with the same threshold. I'm confused by the inconsistency. Which one should I use?

**Comment by zwyking** [comment]
hi,i want to know how to generate it . Could you tell me how to do?

**Comment by etrulls** [comment]
You're mixing up the training and validation data.

For the validation scenes, we provide a pre-formatted set which, similarly to the test data, is subsampled to 100 images per scene. So if you set the visibility threshold to 0 you will get 100 * 99 / 2 = 4950 pairs. You should not really look at this, it's just used to compile statistics at different co-visibility thresholds (automatically).

You can also use this for training if you want, so we provide the full set, which gives you the largest set of pairs. The download page has separate links for validation and training, for the same scenes.
