### ISSUE TITLE
colmap error:"No such file or directory: 'colmap': 'colmap'", please help

### ISSUE THREAD

**Issue by lixiang123321** [ubc-vision/image-matching-benchmark#16]
when do in the first test :
python run.py --subset=val --json_method=example/configs/example-test.json --run_mode=interactive

error :

COLMAP Feature Import
[Errno 2] No such file or directory: 'colmap': 'colmap'
Traceback (most recent call last):
  File "eval_colmap.py", line 228, in run_colmap_for_bag
    colmap_res = subprocess.run(cmd)
  File "/apps/miniconda3/envs/sfm/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/apps/miniconda3/envs/sfm/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/apps/miniconda3/envs/sfm/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'colmap': 'colmap'

**Comment by etrulls** [comment]
As explained in the documentation, Colmap needs to be compiled and visible in the path. Have you done that?

**Comment by lixiang123321** [comment]
Thanks @etrulls .
I've followed the install guide, and solve the problem. [https://colmap.github.io/install.html](url)

Then I get another error:

> COLMAP Feature Import
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
*** Aborted at 1587365435 (unix time) try "date -d @1587365435" if you are using GNU date ***
PC: @     0x7fdec6b8d337 __GI_raise
*** SIGABRT (@0x692f) received by PID 26927 (TID 0x7fdece622940) from PID 26927; stack trace: ***
    @     0x7fdec8c2f5f0 (unknown)
    @     0x7fdec6b8d337 __GI_raise
    @     0x7fdec6b8ea28 __GI_abort
    @     0x7fdec749d7d5 (unknown)
    @     0x7fdec749b746 (unknown)
    @     0x7fdec749b773 (unknown)
    @     0x7fdec749b993 (unknown)
    @     0x7fdec74f0907 (unknown)
    @     0x7fdec74b9804 (unknown)
    @     0x7fdec74ae6fc (unknown)
    @     0x7fdec74af8e2 (unknown)
    @     0x7fdecddef922 (unknown)
    @     0x7fdecddf12af (unknown)
    @           0x7808d8 colmap::GetParentDir()
    @           0x785d59 colmap::OptionManager::Check()
    @           0x791d03 colmap::OptionManager::Parse()
    @           0x5a2c8b RunFeatureImporter()
    @           0x59a42d main
    @     0x7fdec6b79505 __libc_start_main
    @           0x59dd47 (unknown)
 -- COLMAP failed to import features!
Traceback (most recent call last):
  File "eval_colmap.py", line 230, in run_colmap_for_bag
    raise RuntimeError(' -- COLMAP failed to import features!')
RuntimeError:  -- COLMAP failed to import features!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "eval_colmap.py", line 320, in <module>
    main(cfg)
  File "eval_colmap.py", line 306, in main
    run_colmap_for_bag(cfg)
  File "eval_colmap.py", line 272, in run_colmap_for_bag
    raise RuntimeError('Parts of colmap runs returns failed state!')
RuntimeError: Parts of colmap runs returns failed state!

and fix the problem `locale::facet::_S_create_c_locale name not valid` with :
`export LC_ALL=“C"`

Thanks again, @etrulls .
