### ISSUE TITLE
how to set json_label and match_name parameters

### ISSUE THREAD

**Issue by InstantWindy** [ubc-vision/image-matching-benchmark#18]
Hi, what do json_label and match_name parameters mean? In the run.py, I don't find the use of json_label parameter, except for output. So, how to set json_label and match_name parameters. Thanks

**Comment by etrulls** [comment]
`json_label` is simply what the results file is called.

`match_name` is relevant only if you want to use custom matches (i.e. if you set `"use_custom_matches": true` in your config file), in which case you have to use the same name as when you import it into the benchmark with `import_features.py`.
