### ISSUE TITLE
Does the version of opencv matter?

### ISSUE THREAD

**Issue by JustWon** [ubc-vision/image-matching-benchmark#19]
I run the following command and got some error related to opencv.

`python run.py --subset=val --json_method=example/configs/my-example-test.json --run_viz=True --run_mode=interactive`

![image](https://user-images.githubusercontent.com/14357526/80683303-f978ef00-8afe-11ea-9d2e-5a399c6ee996.png)

I attached the config file that I used.
https://www.dropbox.com/s/q1a96ozacxcir5c/my-example-test.json?dl=0

the evaluation by "example-test.json" worked fine but I want to evaluate the deep-learning based features like hardnet, sosnet, etc..

I imported the extracted features from those via import_features.py and executed the run.py and got the above errors.

**Comment by ducha-aiki** [comment]
It is weird error. It might be that your OpenCV installation is not complete, or descriptors are not numpy float32

**Comment by JustWon** [comment]
currently, I found out that this works well with superpoint but not with hardnet and sosnet. (in my environment)

**Comment by etrulls** [comment]
The matcher complains if it doesn't get the type it expects, but it should work with hardnet and sosnet. You can put a breakpoint in there and try casting the array?

**Comment by JustWon** [comment]
Interestingly, the type of descriptor looks float32.. but the same error occurs.

![image](https://user-images.githubusercontent.com/14357526/80693348-d4d84380-8b0d-11ea-8177-00dcdd0a0da2.png)

**Comment by etrulls** [comment]
Weird. You can disable the parallel call [here](https://github.com/vcg-uvic/image-matching-benchmark/blob/3a2f8c144aeaf9fd2d5b302b28c144be8ee769fe/compute_match.py#L92) and use a simple loop instead, for debugging. That's all I can think of.

**Comment by JustWon** [comment]
After several tests, I found out that the "siftdef" for the keypoint is working in my case.
"sift8k" produces the above error.. I have no idea yet.

**Comment by etrulls** [comment]
That's strange, there should be no difference at all, because the descriptors are computed after the keypoint detection step. Maybe something went wrong with a specific file? I would just try to regenerate it before debugging it any further.

**Comment by InstantWindy** [comment]
@JustWon Hi, I have the same error, so how do you solve it?
