### ISSUE TITLE
repeatability and matching scores

### ISSUE THREAD

**Issue by InstantWindy** [ubc-vision/image-matching-benchmark#20]
1) The only indicators for this evaluation are repeatability and matching scores? How to view the repeatability and matching scores for the "rootsift-upright-2k-degensac-inlier-th-0.1.json" files generated in the packed Val folder? In the generated files, there is much repeatability parameter, what does it mean. 
2) "qt_auc_05_th_0.1, qt_auc_10_th_0.1 ,qt_01_10_th_0.2, qt_auc_05_th_0.2" . What do these parameters mean.
Thanks.

**Comment by etrulls** [comment]
This is explained on the [website](https://vision.uvic.ca/image-matching-challenge/benchmark/), and in the [paper](https://arxiv.org/abs/2003.01587). In the interest of time, I will not repeat this here. They also explain that repeatability and matching score are only computed as a baseline and not at all what we use for evaluation.

The "th" is the co-visibility threshold. We use 0.1 in the challenge.
