### ISSUE TITLE
I have question about 'images.txt' when debug the run.py

### ISSUE THREAD

**Issue by kkzh2313** [ubc-vision/image-matching-benchmark#26]
_An error occurred while running to line 212 of run.py, as described below during debugging:_
Traceback (most recent call last):
  File "compute_feature.py", line 172, in <module>
    main(cfg)
  File "compute_feature.py", line 105, in main
    images_list = get_fullpath_list(data_dir, 'images')
  File "/home/xhzh/Desktop/share_with_vm/代码/特征点_描述子/image-matching-benchmark-master/image-matching-benchmark-master/utils/path_helper.py", line 486, in get_fullpath_list
    fullpath_list = parse_file_to_list(list_file, data_dir)
  File "/home/xhzh/Desktop/share_with_vm/代码/特征点_描述子/image-matching-benchmark-master/image-matching-benchmark-master/utils/path_helper.py", line 459, in parse_file_to_list
    with open(file_name, 'r') as f:
**FileNotFoundError: [Errno 2] No such file or directory: '../data/phototourism/reichstag/set_100/images.txt'**
________________________________________________________________________________
I I would like to ask how 'image.txt' was obtained,  this file was not found in the data set downloaded.

**Comment by etrulls** [comment]
You probably downloaded the wrong files? The validation set is [here](https://vision.uvic.ca/imw-challenge/index.md), on the "all sequences" link. It contains that file.

**Comment by kkzh2313** [comment]
yes, I downloaded the data from the link you said and chose the the data of Reichstag(0.3G) from the validation set. Its file directory is:
reichstag
-dense
  --images
    ---05461164_9050854768.jpg
    ---*****.jpg
    .......
  --sparse
    ---cameras.bin
    ---images.bin
    ---points3D.bin
  --stereo
     ---depth_maps
     ---depth_maps_clean_300_th_0.10
     ---pairs_dilation-0.00-fixed2.h5
______________________________________________________________________________________
However, I did not find the 'images.txt'. Does it exist in the full validation data('all sequences')?

**Comment by etrulls** [comment]
I literally just answered that :), yes, the file's there.
You downloaded the raw dumps which can we used for training. The data formatted for validation is on the link I gave you. [This one](https://vision.uvic.ca/imw-challenge/ValidationData/imw2020-valid.tar.gz).

**Comment by kkzh2313** [comment]
thank you very much!
