### ISSUE TITLE
How did  the 2d points(image.xys)   come about?

### ISSUE THREAD

**Issue by DIVE128** [ubc-vision/image-matching-benchmark#29]
In example/training_data/parse_data.ipynb, how did 2d points(image.xys) come about? Key point detection like sift?

**Comment by kmyi** [comment]
This is a benchmarking framework. We expect the evaluated methods to provide them. Please also see the baselines repository.

Thanks,
Kwang

**Comment by DIVE128** [comment]
> This is a benchmarking framework. We expect the evaluated methods to provide them. Please also see the baselines repository.
> 
> Thanks,
> Kwang

thanks
