### ISSUE TITLE
[question] keypoints coordinate convention

### ISSUE THREAD

**Issue by santelelle** [ubc-vision/image-matching-benchmark#35]
In the benchmark _submit_ section it is stated:

> The keypoint file must contain an array with N keypoints with 0-indexed (x, y) coordinates, with the origin in the top left corner.

Does this mean that the top-left corner of the top-left pixel has coordinates (0, 0) and the center of this same pixel is at (0.5, 0.5)?

**Comment by ducha-aiki** [comment]
No. It just means, not matlab 1-based indexing :)

**Comment by santelelle** [comment]
Ok thanks :)
So which convention should I use when submitting keypoints coordinate? 

- A: the top-left corner of the top-left pixel has coordinate (x, y)=(0, 0), therefore the center of the same pixel has coordinate (0.5, 0.5) --> ETH3D/Colmap convention

- B: the top-left corner of the top-left pixel has coordinate (x, y)=(-0.5, -0.5), therefore the center of the same pixel has coordinate (0, 0) --> OpenCV convention

**Comment by ducha-aiki** [comment]
Top-left at (0,0)

**Comment by santelelle** [comment]
Ok thanks, so to close this the right convention is the **A**
