### ISSUE TITLE
Hi, I don't know what is the meaning of '512' according to the descriptor

### ISSUE THREAD

**Issue by Devoe-97** [ubc-vision/image-matching-benchmark#36]
my descriptors.h5 contains descriptors of num_keypoints * 256 
when I run submission_validator.py, it shows "Descriptors size is larger than 512 bytes"

**Comment by ducha-aiki** [comment]
Thank you, it seems that we haven`t updated our validator w.r.t the recent rule change. You can ignore this message.
P.S. 512 bytes == 128 dim desc * 4 byte (per float32)

**Comment by Devoe-97** [comment]
so the value in descriptors.h5 is  num_keypoints * 256?

**Comment by ducha-aiki** [comment]
Sorry, I don't know what is value for your kind of descriptors

**Comment by Devoe-97** [comment]
one more question
the name of image is a string
and I don't know which is LARGEST_KEY or SMALLEST_KEY

**Comment by etrulls** [comment]
Alphabetically. The keys are image names, minus the extension. So if you have `image1.jpg` and `image2.jpg` the key in the matches file is `matches2-matches1`. It's explained [here](https://www.cs.ubc.ca/research/image-matching-challenge/2021/submit/).

And as Dmytro said, the descriptor rule was just lifted, so no issues there.
