### ISSUE TITLE
md5 of training data?

### ISSUE THREAD

**Issue by willer94** [ubc-vision/image-matching-benchmark#37]
Could you please provide the md5 of the training data? I downloaded the .tar.gz files, but the sizes of several files are  not equal to the size claimed on the website.

**Comment by kmyi** [comment]
e437b756b231eecb505a97e345e9bd9a  imc-2021-test-public-phototourism.tar.gz
acaf216ce0cf093b2cd740e1b2c60b78  imc-2021-test-public-pragueparks.tar.gz
3602292142140a6d0d78e58bae1f9c82  imc-2021-validation-phototourism.tar.gz
541bc9cf892fd9241dacbd2cfbc73af5  imc-2021-validation-pragueparks.tar.gz
4e3962c286f2b7b8a046324efd0b382c  imc-2021-test-public-googleurban.tar.gz
3a7d5f60be5d74b6cbd7ba0cdb3d844b  imc-2021-validation-googleurban.tar.gz

@jyh2005xx Not urgent, but can you include this in the website?

**Comment by willer94** [comment]
ok, thanks!
