### ISSUE TITLE
[Dataset] prague_old_town_square (14G) on IMC-PT seems incomplete

### ISSUE THREAD

**Issue by Jia-Wei-Liu** [ubc-vision/image-matching-benchmark#40]
Hi,
I downloaded Image Matching Challenge PhotoTourism (IMC-PT) 2020 dataset from https://www.cs.ubc.ca/%7Ekmyi/imw2020/data.html
I find that prague_old_town_square (14G) seems to be incomplete. The downloaded tar.gz file size is 7.6GB rather than 14GB. This landmark does not have pairs-dilation-0.00-fixed2.h5, and the depth maps seem incomplete, too. Could you please check that? Thank you very much!
By the way, could you please give some instruction on how to generate pairs-dilation-0.00-fixed2.h5? Thank you!

**Comment by etrulls** [comment]
It's always been like that, unfortunately. There was some issue generating the dataset, we never got around to fixing it, and we've lost access to some of the required files by now. Just don't use it. I'll make a note to delete it.

**Comment by Jia-Wei-Liu** [comment]
Got it. Thank you very much for your quick reply!
