### ISSUE TITLE
Generating the SfM bags for new scenes

### ISSUE THREAD

**Issue by sarlinpe** [ubc-vision/image-matching-benchmark#41]
I want to do some additional validation of the SfM task using training scenes of the Phototourism dataset. How should I generate the bags? The paper says that the bags _are randomly sampled from the original set of 100 images per scene – with a co-visibility check_ (Section 4.5). I tried to:
1. pick subsets where all images share 3D points: this is too restrictive and yields very few to no bags of 25 images.
2. perform random walks on the visibility graph with a minimum ratio of covisible 3D points: this yields chains that are more difficult to reconstruct than the bags in the validation scenes.

Any pointer or code would be much appreciated, thanks!

**Comment by etrulls** [comment]
It was pretty simple, from what I recall. We refactored the code and there's a new script to do this, but I can't find it right now. @jyh2005xx can you please point Paul-Edouard to it? Thanks.

**Comment by sarlinpe** [comment]
@jyh2005xx helped out, thanks!

**Comment by biggiantpigeon** [comment]
> @jyh2005xx helped out, thanks!

Hi, I'm trying to generating my own test set. Could you please show me the script you use? I am also wondering how to generate the folders like 'calibration', 'depth_maps' in a scene, could you give me some hint? Thanks a lot!
