### ISSUE TITLE
Generate /dense/stereo/pairs-dilation-0.00-fixed2.h5 for new Scenes

### ISSUE THREAD

**Issue by DIVE128** [ubc-vision/image-matching-benchmark#43]
Hellow, the file **/dense/stereo/pairs-dilation-0.00-fixed2.h5** contains a Data Structure of **[bbox1, bbox2, visibility1, visibility2, # of shared matches]**. Could you provide the script to generate this file?

**Comment by etrulls** [comment]
The procedure is trivial -- it's explained in the [paper](https://arxiv.org/pdf/2003.01587.pdf) (Sec. 3.2, with examples in Fig. 5). I have no idea where the code is, it's very old.
