### ISSUE TITLE
how to benchmark hardnet features?

### ISSUE THREAD

**Issue by JustWon** [ubc-vision/image-matching-benchmark#5]
Currently I imported the hardnet feature via import_features.py . 

I found out that the several new folders and files were created at benchmark-results directory.
![image](https://user-images.githubusercontent.com/14357526/77829082-fdfa6280-7162-11ea-8dcf-10dfa9fe8d07.png)

Now I want to evaluate the features from hardnet by run.py .

After looking into the run.py file, I realized that the compute_feature.py was called and 
some routine for hardnet is necessary in compute_per_img_file function.
![image](https://user-images.githubusercontent.com/14357526/77829062-db684980-7162-11ea-85e4-0645bc9ea8cd.png)

Should I need to implement this routine by myself or do you provide them?

My ultimate goal is to perform the benchmark on my own descriptor network.

Thanks you!

**Comment by etrulls** [comment]
compute_feature is only called if the features do not exist already. You probably didn't pass the correct settings. Your config file should have "sift8k" as keypoints, "hardnet" as descriptors, and the correct number of keypoints (2048), and the features should exist for the datasets you're trying to call (val or test). Please double-check your config file and copy-paste it here if you can't figure it out.
