### ISSUE TITLE
Mistake in text description of the pose error metric

### ISSUE THREAD

**Issue by chrisoffner3d** [ubc-vision/image-matching-benchmark#51]
The sentence

> To measure the accuracy for a given pair of images, we compute the angular error between the **estimated ground truth translation vectors** and the **estimated and ground truth translation vectors**, and take the largest of the two.

doesn't seem quite right, does it?

https://github.com/ubc-vision/image-matching-benchmark/blob/da05d98f2a39d848ce29124fd521cdd659718c36/README.md?plain=1#L310

**Comment by ducha-aiki** [comment]
Thanks, fixed. One of the translation should be rotation
