### ISSUE TITLE
Which one is the "CV-DoG" mentioned in the paper?

### ISSUE THREAD

**Issue by Guptajakala** [ubc-vision/image-matching-benchmark#6]

**Comment by etrulls** [comment]
Open CV Difference of Gaussians (SIFT).

**Comment by Guptajakala** [comment]
@etrulls
https://arxiv.org/pdf/2003.01587.pdf
In figure6, I see another CV-SIFT other than CV-DoG. What's the difference between Open CV Difference of Gaussians (SIFT) and CV-SIFT?

**Comment by etrulls** [comment]
"DoG" is shorthand for the SIFT **detector** (we call it "CV-DoG" as we also have a few experiments with VLFeat's implementation of DoG). So for instance "CV-DoG/Hardnet" means Hardnet descriptors on SIFT (DoG) keypoints. "CV-SIFT" means SIFT descriptors on SIFT keypoints.

**Comment by Guptajakala** [comment]
@etrulls Now I get it, thank you very much!
