### ISSUE TITLE
depth data

### ISSUE THREAD

**Issue by zwyking** [ubc-vision/image-matching-benchmark#7]
Hello. i have a question about what the meaning of the pids in depth data？

**Comment by etrulls** [comment]
Missed this issue. I'm sorry, I don't understand the question?

**Comment by zwyking** [comment]
there is an attribute pids of the Image , i want to understand what is meaning of the data of pids

**Comment by etrulls** [comment]
Where? I opened an h5 depth map file and I don't see anything like this. Please be specific when asking for help.

**Comment by zwyking** [comment]
oh ，sorry! I mistaken the attribute.
`p = images[idx].xys`
It's the  images[idx].xys.

**Comment by etrulls** [comment]
I assume that comes from reading the binary files provided by colmap. The "xys" are keypoint locations, you can see how to use them [here](https://github.com/vcg-uvic/image-matching-benchmark/blob/master/example/training_data/parse_data.ipynb) (which I guess is where you got that snippet from?). Should be pretty self-explanatory, but please refer to the Colmap documentation if still in doubt.

**Comment by zwyking** [comment]
ok!Thanks very much~
