### ISSUE TITLE
What and Where are the "keys-th-{:0.1f}.npy" file to generate pairs when compute_matches?

### ISSUE THREAD

**Issue by feymanpriv** [ubc-vision/image-matching-benchmark#8]
def get_pairs_per_threshold(data_dir):
    pairs = {}
    for th in np.arange(0, 1, 0.1):
        pairs['{:0.1f}'.format(th)] = np.load(
            '{}/new-vis-pairs/keys-th-{:0.1f}.npy'.format(data_dir, th))
    return pairs

I cannot find the file in gt data downloaded from the link you have provided.

**Comment by etrulls** [comment]
They are there, I just checked. [This](https://vision.uvic.ca/imw-challenge/ValidationData/imw2020-valid.tar.gz) is the link you should be using. (Maybe you downloaded the full reconstructions for the validation scenes?)

**Comment by feymanpriv** [comment]
> They are there, I just checked. [This](https://vision.uvic.ca/imw-challenge/ValidationData/imw2020-valid.tar.gz) is the link you should be using. (Maybe you downloaded the full reconstructions for the validation scenes?)

aha, thanks!
