### ISSUE TITLE
Some questions about the submission

### ISSUE THREAD

**Issue by feymanpriv** [ubc-vision/image-matching-benchmark#9]
1. Is Scores of keypoints necessary for a submission?
2. Is it valid to just submit keypoints and corresponding descriptors (including config json file show the parameter of built-in methods or custom methods) and the system performs the matching process automatically?
3. I see your geom methods include custom and others such as pyransac, densac and etc. I wonder whether the custom ones are opencv methods. 
3. If we provide kps, descriptors and matches, system will directly provide the match file to evaluation and do not perform the matching process any more? If so, what format should the config file be? Since we may use other ways to do the filtering rather than ratio test. 

Can you provide a more clear submission file to the leaderboard which just includes the benchmark need of different formats the system support?

**Comment by ducha-aiki** [comment]
1. Yes. However, you can fill it with ones.
2. Yes. 
3. No, they are not OpenCV. Please, see out paper for the benchmark, specifically  https://arxiv.org/pdf/2003.01587.pdf
![image](https://user-images.githubusercontent.com/4803565/78897465-808ff580-7a72-11ea-8fae-ce0d17ab8eb2.png) 
OpenCV ransac is very bad.
4. use {filtering: type: "none"}

Regarding submission file: please, follow the instruction in baselines repo and you will get the submission 
https://github.com/vcg-uvic/image-matching-benchmark-baselines

**Comment by feymanpriv** [comment]
> 1. Yes. However, you can fill it with ones.
> 2. Yes.
> 3. No, they are not OpenCV. Please, see out paper for the benchmark, specifically  https://arxiv.org/pdf/2003.01587.pdf
>    ![image](https://user-images.githubusercontent.com/4803565/78897465-808ff580-7a72-11ea-8fae-ce0d17ab8eb2.png)
>    OpenCV ransac is very bad.
> 4. use {filtering: type: "none"}
> 
> Regarding submission file: please, follow the instruction in baselines repo and you will get the submission
> https://github.com/vcg-uvic/image-matching-benchmark-baselines

Sorry to bother you,
Following the repo, we will have the final files as: 
config_file.json
feature_path/british_museum/keypoints.h5
feature_path/british_museum/descriptors.h5
feature_path/british_museum/scores.h5
...

Then, how to name the json file and how to organize the files and finally tar them?

**Comment by ducha-aiki** [comment]
Just tar them and send. Name json by method name, but basically any name you want.

**Comment by feymanpriv** [comment]
OK, thanks
